/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Karnataka",
  "stateCode": 29,
  "slug": "karnataka",
  "accent": "#d97706",
  "accentSoft": "#fdeccf",
  "division": "taluk",
  "nativeLang": "kn",
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    },
    {
      "name": "Telangana",
      "slug": "telangana",
      "url": "../../telangana/web/index.html"
    },
    {
      "name": "Tamil Nadu",
      "slug": "tamil_nadu",
      "url": "../../tamil_nadu/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://github.com/ramSeraph/opendata"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T14:48:10Z",
  "counts": {
    "districts": 31,
    "mandals": 240,
    "villages": 30771,
    "with_pincode": 29453,
    "with_local_names": 60
  }
};
