/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Karnataka",
  "stateCode": 29,
  "slug": "karnataka",
  "accent": "#d97706",
  "accentSoft": "#fdeccf",
  "division": "taluk",
  "nativeLang": "kn",
  "cadastre": {
    "url": "https://pub-f9d4d8c3e04d4318832ab39d095575b6.r2.dev/KGISMAPS_KN_Cadastrals.pmtiles",
    "sourceLayer": "KGISMAPS_KN_Cadastrals",
    "minZoom": 11,
    "tileMaxZoom": 13,
    "fields": {
      "survey": "Surveynumber_Old",
      "villageCode": "LGD_VillageCode",
      "area": "SHAPE.STArea()",
      "id": [
        "OBJECTID",
        "KGISCadastralID"
      ]
    },
    "attribution": "Cadastre &copy; KGIS (Karnataka, CC0) via <a href=\"https://github.com/ramSeraph/indian_cadastrals\" target=\"_blank\" rel=\"noopener\">datameet/ramSeraph</a>",
    "fmb": {
      "name": "Bhoomi survey documents",
      "url": "https://landrecords.karnataka.gov.in/service130/"
    }
  },
  "mandi": {
    "url": "https://raw.githubusercontent.com/mchittineni/india-village-finder/refs/heads/data/mandi-prices/karnataka.json"
  },
  "overlays": [
    {
      "id": "gw",
      "labelKey": "ov_gw",
      "url": "https://bhuvan-vec1.nrsc.gov.in/bhuvan/wms",
      "wms": {
        "layers": "gw:AP_LGEOM,gw:TS_LGEOM,gw:KA_LGEOM,gw:TN_LGEOM",
        "format": "image/png",
        "transparent": true,
        "version": "1.1.1"
      },
      "opacity": 0.6,
      "maxZoom": 15,
      "attribution": "Groundwater prospects: <a href=\"https://bhuvan.nrsc.gov.in\" target=\"_blank\" rel=\"noopener\">Bhuvan, NRSC/ISRO</a>"
    },
    {
      "id": "soil",
      "labelKey": "ov_soil",
      "url": "https://maps.isric.org/mapserv?map=/map/wrb.map",
      "wms": {
        "layers": "MostProbable",
        "format": "image/png",
        "transparent": true,
        "version": "1.3.0"
      },
      "opacity": 0.65,
      "maxZoom": 14,
      "attribution": "Soil: <a href=\"https://soilgrids.org\" target=\"_blank\" rel=\"noopener\">ISRIC SoilGrids</a> (CC BY 4.0)"
    }
  ],
  "boundaryTiles": null,
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    },
    {
      "name": "Telangana",
      "slug": "telangana",
      "url": "../../telangana/web/index.html"
    },
    {
      "name": "Tamil Nadu",
      "slug": "tamil_nadu",
      "url": "../../tamil_nadu/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://data.gov.in/ (Open Government Data platform)"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T15:10:26Z",
  "counts": {
    "districts": 31,
    "mandals": 240,
    "villages": 30771,
    "with_pincode": 29453,
    "with_local_names": 60
  }
};
