/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Telangana",
  "stateCode": 36,
  "slug": "telangana",
  "accent": "#0f9d58",
  "accentSoft": "#e3f6ec",
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://github.com/ramSeraph/opendata"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T08:36:25Z",
  "counts": {
    "districts": 33,
    "mandals": 621,
    "villages": 11308
  }
};
