/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Telangana",
  "stateCode": 36,
  "slug": "telangana",
  "accent": "#0f9d58",
  "accentSoft": "#e3f6ec",
  "division": "mandal",
  "nativeLang": "te",
  "cadastre": {
    "url": "https://pub-f9d4d8c3e04d4318832ab39d095575b6.r2.dev/TRACGIS_Bhunaksha_Cadastrals.pmtiles",
    "sourceLayer": "TRACGIS_Bhunaksha_Cadastrals",
    "minZoom": 11,
    "tileMaxZoom": 13,
    "fields": {
      "survey": "Parcel_num",
      "village": "V_Name",
      "mandal": "M_Name",
      "district": "D_Name",
      "area": "Shape_Area",
      "id": [
        "OBJECTID",
        "OBJECTID_12",
        "OBJECTID_1"
      ]
    },
    "attribution": "Cadastre &copy; TRACGIS (Telangana Bhunaksha, CC0) via <a href=\"https://github.com/ramSeraph/indian_cadastrals\" target=\"_blank\" rel=\"noopener\">datameet/ramSeraph</a>",
    "fmb": {
      "name": "Bhu Bharati",
      "url": "https://bhubharati.telangana.gov.in/gis/"
    }
  },
  "mandi": {
    "url": "https://raw.githubusercontent.com/mchittineni/india-village-finder/refs/heads/data/mandi-prices/telangana.json"
  },
  "schemes": {
    "url": "https://raw.githubusercontent.com/mchittineni/india-village-finder/refs/heads/data/farmer-schemes/telangana.json"
  },
  "farm": {
    "season": "Kharif 2026",
    "fertilizers": [
      {
        "name": "Urea (45 kg)",
        "price": "₹266.50"
      },
      {
        "name": "DAP (50 kg)",
        "price": "₹1,350"
      }
    ],
    "links": [
      {
        "labelKey": "farm_stock_link",
        "url": "https://urvarak.nic.in/"
      },
      {
        "labelKey": "farm_shc_link",
        "url": "https://soilhealth.dac.gov.in/"
      }
    ]
  },
  "overlays": [
    {
      "id": "gw",
      "labelKey": "ov_gw",
      "url": "https://bhuvan-vec1.nrsc.gov.in/bhuvan/wms",
      "wms": {
        "layers": "gw:AP_LGEOM,gw:TS_LGEOM,gw:KA_LGEOM,gw:TN_LGEOM",
        "format": "image/png",
        "transparent": true,
        "version": "1.1.1"
      },
      "opacity": 0.6,
      "maxZoom": 15,
      "attribution": "Groundwater prospects: <a href=\"https://bhuvan.nrsc.gov.in\" target=\"_blank\" rel=\"noopener\">Bhuvan, NRSC/ISRO</a>"
    },
    {
      "id": "soil",
      "labelKey": "ov_soil",
      "url": "https://maps.isric.org/mapserv?map=/map/wrb.map",
      "wms": {
        "layers": "MostProbable",
        "format": "image/png",
        "transparent": true,
        "version": "1.3.0"
      },
      "opacity": 0.65,
      "maxZoom": 14,
      "attribution": "Soil: <a href=\"https://soilgrids.org\" target=\"_blank\" rel=\"noopener\">ISRIC SoilGrids</a> (CC BY 4.0)"
    }
  ],
  "boundaryTiles": null,
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    },
    {
      "name": "Karnataka",
      "slug": "karnataka",
      "url": "../../karnataka/web/index.html"
    },
    {
      "name": "Tamil Nadu",
      "slug": "tamil_nadu",
      "url": "../../tamil_nadu/web/index.html"
    },
    {
      "name": "Kerala",
      "slug": "kerala",
      "url": "../../kerala/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://data.gov.in/ (Open Government Data platform)"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T15:10:24Z",
  "counts": {
    "districts": 33,
    "mandals": 621,
    "villages": 11308,
    "with_pincode": 11290,
    "with_local_names": 11226
  }
};
