/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Telangana",
  "stateCode": 36,
  "slug": "telangana",
  "accent": "#0f9d58",
  "accentSoft": "#e3f6ec",
  "division": "mandal",
  "nativeLang": "te",
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    },
    {
      "name": "Karnataka",
      "slug": "karnataka",
      "url": "../../karnataka/web/index.html"
    },
    {
      "name": "Tamil Nadu",
      "slug": "tamil_nadu",
      "url": "../../tamil_nadu/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://github.com/ramSeraph/opendata"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T15:10:24Z",
  "counts": {
    "districts": 33,
    "mandals": 621,
    "villages": 11308,
    "with_pincode": 11290,
    "with_local_names": 11226
  }
};
