/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Andhra Pradesh",
  "stateCode": 28,
  "slug": "andhra_pradesh",
  "accent": "#1f6feb",
  "accentSoft": "#eaf2ff",
  "siblings": [
    {
      "name": "Telangana",
      "slug": "telangana",
      "url": "../../telangana/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://github.com/ramSeraph/opendata"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T08:13:48Z",
  "counts": {
    "districts": 28,
    "mandals": 688,
    "villages": 17957
  }
};
