/* generated by scraper/pipeline.py - do not edit */
window.VF_CONFIG = {
  "state": "Tamil Nadu",
  "stateCode": 33,
  "slug": "tamil_nadu",
  "accent": "#dc2626",
  "accentSoft": "#fdeaea",
  "division": "taluk",
  "nativeLang": "ta",
  "siblings": [
    {
      "name": "Andhra Pradesh",
      "slug": "andhra_pradesh",
      "url": "../../andhra_pradesh/web/index.html"
    },
    {
      "name": "Telangana",
      "slug": "telangana",
      "url": "../../telangana/web/index.html"
    },
    {
      "name": "Karnataka",
      "slug": "karnataka",
      "url": "../../karnataka/web/index.html"
    }
  ],
  "source": {
    "name": "Local Government Directory (LGD)",
    "url": "https://lgdirectory.gov.in",
    "mirror": "https://github.com/ramSeraph/opendata"
  },
  "sourceDate": "25Jun2026",
  "generatedAt": "2026-06-26T14:05:30Z",
  "counts": {
    "districts": 38,
    "mandals": 317,
    "villages": 18681,
    "with_pincode": 18652,
    "with_local_names": 1516
  }
};
